### ISSUE TITLE
arm64 runTests --proccontrol does not produce sensible results

### ISSUE THREAD

**Issue by ikitayama** [dyninst/testsuite#20] opened 2016-12-05 21:15 UTC
@wrwilliams @ssunny7 
I'm on the master of testsuite and here's the CMake output 

```
-- Checking for C++11 flags for GNU
-- Disabling Boost's own CMake--known buggy in many cases
-- Boost version: 1.60.0
-- Dyninst includes: /usr/local/lib/cmake/Dyninst/../../../include
-- Project source dir: /home/itaru.kitayama/projects/testsuite
-- Mutatee gcc: /usr/bin/gcc
-- Mutatee g++: /usr/bin/g++
-- Mutatee icc: M_intel_cc-NOTFOUND
-- Mutatee icpc: M_intel_CC-NOTFOUND
-- Mutatee pgcc: M_pg_cc-NOTFOUND
-- Mutatee pgCC: M_pg_cxx-NOTFOUND
-- Mutatee mpicc: /usr/lib64/openmpi/bin/mpicc
-- Mutatee mpicxx: /usr/lib64/openmpi/bin/mpicxx
-- Mutatee mpixlc: M_mpi_xlc-NOTFOUND
-- Mutatee mpixlcxx: M_mpi_xlcxx-NOTFOUND
-- Configuring done
-- Generating done
-- Build files have been written to: /home/itaru.kitayama/projects/testsuite
```

**Comment by wrwilliams** [comment] 2016-12-05 21:45
That should produce mutatees (there would be issues if all the available mutatee compilers were coming up NOTFOUND). Are you running from the installed bin/testsuite directory? If you don't do that, the mutatees will also not be found (as they're scattered throughout the build tree and not in the top-level build directory).

**Comment by ikitayama** [comment] 2016-12-05 22:14
I wasn't, but running it from the /usr/local/bin/testsuite did not help either.
Is the --proccontrol option explained in the man page?

**Comment by wrwilliams** [comment] 2016-12-05 22:32
It should be explained in the Dyninst manual's section on building and testing, yes. And my memory was playing tricks on me; it's -proccontrol (single dash) and similar, not double dash.

**Comment by ikitayama** [comment] 2016-12-06 05:02
I've been testing various combinations of options so I can avoid disabling tests in proccontrol
component, but still can't obtain sensible results.

**Comment by hainest** [comment] 2020-11-08 00:49
Unable to reproduce using current HEAD of master. Closing. If this continues to be an issue for you, please either re-open this issue or submit a new one.

**Closed by hainest** 2020-11-08 00:49 UTC
